function data = import_storm_data(filename,datalines)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\kv220\Desktop\MATLAB  Specialization\Exploratory Data Analysis\StormEvents\StormEvents_2013.csv
%
% Auto-generated by MATLAB on 30-Mar-2020 21:20:21

%% Input Handling
if nargin<2
    datalines = [2,inf];
end
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = datalines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "State", "Year", "Month", "Event_Type", "Begin_Date_Time", "Var8", "End_Date_Time", "Var10", "Var11", "Var12", "Var13", "Var14", "Property_Cost", "Var16", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Var22", "Event_Narrative"];
opts.SelectedVariableNames = ["State", "Year", "Month", "Event_Type", "Begin_Date_Time", "End_Date_Time", "Property_Cost", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Event_Narrative"];
opts.VariableTypes = ["string", "string", "categorical", "double", "categorical", "categorical", "datetime", "string", "datetime", "string", "string", "string", "string", "string", "double", "string", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var16", "Var22", "Event_Narrative"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "State", "Month", "Event_Type", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var16", "Var22", "Event_Narrative"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "End_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
data = readtable(filename, opts);


%% Clear temporary variables
clear opts

end