function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Apr-2020
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [617313 657314 692314 724356 735314 ];
backgroundInd = [285231 285233 287231 287236 289231 291240 297230 305230 312270 331230 337306 371370 372236 408243 414457 444506 459531 471258 481563 501588 512600 524271 527610 538621 548626 557633 559634 561637 564638 565638 567641 568641 569641 571641 579744 579748 579751 581637 581753 584738 589730 591754 592628 597721 604710 611613 611703 611754 617694 621691 622280 622754 629683 632591 647664 649754 665644 669563 669753 671280 687394 687396 688394 689394 691393 691394 692393 694393 697393 698543 699393 701280 702606 705393 712393 714747 724393 731523 735393 741576 745393 749513 758511 759391 759560 764391 765511 772388 775511 778544 779388 785513 787733 788516 792386 794517 794520 794531 795524 812383 849713 852377 884701 901368 935674 961354 974647 1007613 1018348 1042587 1058346 1062570 1085551 1089348 1101533 1105351 1109513 1114358 1118368 1121488 1122380 1127391 1128477 1129463 1131411 1131451 1132444 1134430 ];
L = superpixels(X,7620,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Flood fill
row = 336;
column = 723;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1) = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2) = (in(:,:,2) + 86.1827) / 184.4170;  % a* range is [-86.1827,98.2343].
out(:,:,3) = (in(:,:,3) + 107.8602) / 202.3382;  % b* range is [-107.8602,94.4780].

end
